import { useMemo, useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Check, Clipboard, Sparkles } from 'lucide-react';
import { db } from '../db';
import { PageHeader } from '../components/PageHeader';
import { stripHtml } from '../lib/text';

export function AssistantPage(){
  const data=useLiveQuery(async()=>({entries:await db.entries.toArray(),modules:await db.moduleTypes.toArray(),rules:await db.rules.toArray(),questions:await db.questions.toArray()}),[]);
  const [selected,setSelected]=useState<string[]>(['blight','node_04','clean_water','breakers','weavers']);const [moduleFilter,setModuleFilter]=useState('all');const [maxChars,setMaxChars]=useState(12000);const [includeRules,setIncludeRules]=useState(true);const [includeQuestions,setIncludeQuestions]=useState(true);const [copied,setCopied]=useState(false);
  const moduleMap=new Map(data?.modules.map(m=>[m.id,m])??[]);
  const prompt=useMemo(()=>{if(!data)return'';const chosen=data.entries.filter(e=>selected.includes(e.id));const chunks=[`You are helping develop the cyberpunk setting “The Analog Schism”. Treat the following records as the only relevant context for this task. Do not silently change canon. Clearly label suggestions as proposals.`,`\n## SELECTED LORE`];for(const e of chosen){chunks.push(`\n### ${e.title} [${e.canonStatus}; ${moduleMap.get(e.moduleTypeId)?.singular??'Lore'}]\n${e.summary}\n${stripHtml(e.body)}`)}if(includeRules){chunks.push('\n## HARD AND STRONG RULES');for(const r of data.rules.filter(r=>r.severity!=='soft'))chunks.push(`- ${r.name}: ${r.rule}`)}if(includeQuestions){chunks.push('\n## UNRESOLVED QUESTIONS');for(const q of data.questions.filter(q=>q.status!=='resolved'))chunks.push(`- ${q.question} — ${q.whyItMatters}`)}chunks.push('\n## INSTRUCTION\nHelp me extend or write within this world. Preserve established constraints, identify any conflict with canon, and keep new ideas modular.');return chunks.join('\n').slice(0,maxChars)},[data,selected,maxChars,includeRules,includeQuestions,moduleMap]);
  async function copy(){await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1500)}
  const visible=data?.entries.filter(e=>moduleFilter==='all'||e.moduleTypeId===moduleFilter).sort((a,b)=>a.title.localeCompare(b.title))??[];
  return <>
    <PageHeader eyebrow="Provider-agnostic AI workflow" title="AI Context Builder" description="Select only the lore needed for a scene or question. Generated context can be pasted into Claude or ChatGPT; suggestions remain drafts until you approve them." actions={<button className="button-primary" onClick={()=>void copy()}>{copied?<Check size={17}/>:<Clipboard size={17}/>} {copied?'Copied':'Copy prompt'}</button>}/>
    <div className="grid gap-4 xl:grid-cols-[390px_minmax(0,1fr)]"><section className="panel p-5"><div className="flex items-center gap-2"><Sparkles size={18} className="text-emerald-300"/><h2 className="font-semibold text-white">Context selection</h2></div><select className="input mt-4" value={moduleFilter} onChange={e=>setModuleFilter(e.target.value)}><option value="all">All module types</option>{data?.modules.map(m=><option key={m.id} value={m.id}>{m.plural}</option>)}</select><div className="mt-3 max-h-[430px] space-y-1 overflow-y-auto pr-1">{visible.map(e=><label key={e.id} className="flex cursor-pointer items-start gap-3 rounded-xl p-2.5 hover:bg-white/[.04]"><input className="mt-1 accent-emerald-300" type="checkbox" checked={selected.includes(e.id)} onChange={event=>setSelected(event.target.checked?[...selected,e.id]:selected.filter(id=>id!==e.id))}/><div><div className="text-sm text-slate-200">{e.title}</div><div className="font-mono text-[10px] uppercase tracking-wider text-slate-600">{moduleMap.get(e.moduleTypeId)?.singular} // {e.canonStatus}</div></div></label>)}</div><div className="mt-4 space-y-3 border-t border-white/10 pt-4"><label className="flex items-center justify-between text-sm text-slate-400"><span>Include rules engine</span><input type="checkbox" checked={includeRules} onChange={e=>setIncludeRules(e.target.checked)} className="accent-emerald-300"/></label><label className="flex items-center justify-between text-sm text-slate-400"><span>Include open questions</span><input type="checkbox" checked={includeQuestions} onChange={e=>setIncludeQuestions(e.target.checked)} className="accent-emerald-300"/></label><label className="block text-xs text-slate-500">Maximum context: {maxChars.toLocaleString()} characters<input className="mt-2 w-full accent-emerald-300" type="range" min="3000" max="30000" step="1000" value={maxChars} onChange={e=>setMaxChars(Number(e.target.value))}/></label></div></section><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="eyebrow">Generated prompt</p><div className="mt-1 text-sm text-slate-400">{selected.length} selected records · {prompt.length.toLocaleString()} characters</div></div><span className="rounded-full border border-amber-300/15 bg-amber-300/5 px-2.5 py-1 text-xs text-amber-200">AI cannot edit canon</span></div><pre className="max-h-[720px] overflow-auto whitespace-pre-wrap p-5 font-mono text-xs leading-6 text-slate-300">{prompt}</pre></section></div>
  </>
}
