import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { CheckCircle2, CircleHelp, Plus, X } from 'lucide-react';
import { db } from '../db';
import { makeId } from '../lib/id';
import { PageHeader } from '../components/PageHeader';
import type { WorldQuestion } from '../types';

export function QuestionsPage() {
  const questions = useLiveQuery(() => db.questions.orderBy('updatedAt').reverse().toArray(), []) ?? [];
  const [filter, setFilter] = useState<'all' | WorldQuestion['status']>('all'); const [open, setOpen] = useState(false); const [resolving, setResolving] = useState<WorldQuestion | null>(null); const [decision, setDecision] = useState('');
  const [form, setForm] = useState({ question:'', whyItMatters:'', consequences:'' });
  const visible = questions.filter((question) => filter === 'all' || question.status === filter);
  async function addQuestion() { if (!form.question.trim()) return; const now=new Date().toISOString(); await db.questions.add({id:makeId('q'),projectId:'project_analog_schism',question:form.question,whyItMatters:form.whyItMatters,clues:[],possibleAnswers:[],affectedEntryIds:[],consequences:form.consequences,status:'open',createdAt:now,updatedAt:now}); setOpen(false); setForm({question:'',whyItMatters:'',consequences:''}); }
  async function resolve() { if (!resolving || !decision.trim()) return; await db.questions.update(resolving.id,{status:'resolved',finalDecision:decision.trim(),updatedAt:new Date().toISOString()}); setResolving(null); setDecision(''); }
  return <>
    <PageHeader eyebrow="Unresolved canon and story pressure" title="Questions & Mysteries" description="Keep unknowns visible until you deliberately resolve them. The app does not confuse an open question with a plot hole." actions={<button className="button-primary" onClick={() => setOpen(true)}><Plus size={17}/> Add question</button>} />
    <section className="panel mb-4 flex flex-wrap gap-2 p-3">{(['all','open','investigating','resolved','parked'] as const).map((value) => <button key={value} className={filter===value?'button-primary !py-2':'button-secondary !py-2'} onClick={() => setFilter(value)}>{value}</button>)}</section>
    <section className="grid gap-4 xl:grid-cols-2">{visible.map((question) => <article key={question.id} className="panel p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`grid size-10 shrink-0 place-items-center rounded-xl border ${question.status==='resolved'?'border-emerald-300/20 bg-emerald-300/10 text-emerald-200':'border-amber-300/20 bg-amber-300/10 text-amber-200'}`}>{question.status==='resolved'?<CheckCircle2 size={19}/>:<CircleHelp size={19}/>}</div><div><div className="eyebrow">{question.status}</div><h2 className="mt-1 font-semibold leading-6 text-white">{question.question}</h2></div></div>{question.status!=='resolved'&&<button className="button-secondary !py-2" onClick={() => setResolving(question)}>Resolve</button>}</div><p className="mt-4 text-sm leading-6 text-slate-400">{question.whyItMatters}</p>{question.clues.length>0&&<div className="mt-4"><div className="eyebrow">Known clues</div><ul className="mt-2 space-y-1 text-xs leading-5 text-slate-500">{question.clues.map((clue)=><li key={clue}>• {clue}</li>)}</ul></div>}{question.possibleAnswers.length>0&&<div className="mt-4 flex flex-wrap gap-2">{question.possibleAnswers.map((answer)=><span key={answer} className="rounded-full border border-white/10 px-2.5 py-1 text-xs text-slate-500">{answer}</span>)}</div>}{question.finalDecision&&<div className="mt-4 rounded-xl border border-emerald-300/15 bg-emerald-300/5 p-3 text-sm text-emerald-100"><span className="font-semibold">Decision:</span> {question.finalDecision}</div>}</article>)}</section>
    {open&&<Modal title="Add worldbuilding question" onClose={()=>setOpen(false)}><input className="input" value={form.question} onChange={(e)=>setForm({...form,question:e.target.value})} placeholder="What remains unknown?"/><textarea className="input min-h-24" value={form.whyItMatters} onChange={(e)=>setForm({...form,whyItMatters:e.target.value})} placeholder="Why does the answer matter?"/><textarea className="input min-h-20" value={form.consequences} onChange={(e)=>setForm({...form,consequences:e.target.value})} placeholder="What changes when this is answered?"/><div className="flex justify-end gap-2"><button className="button-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button-primary" onClick={()=>void addQuestion()}>Add question</button></div></Modal>}
    {resolving&&<Modal title="Resolve canon question" onClose={()=>setResolving(null)}><div className="rounded-xl bg-white/[.035] p-3 text-sm text-slate-300">{resolving.question}</div><textarea autoFocus className="input min-h-32" value={decision} onChange={(e)=>setDecision(e.target.value)} placeholder="State the final decision clearly…"/><p className="text-xs leading-5 text-slate-500">Resolving preserves the original question and records the answer. Create a locked Canon Decision from Settings if this choice must be protected.</p><div className="flex justify-end gap-2"><button className="button-secondary" onClick={()=>setResolving(null)}>Cancel</button><button className="button-primary" onClick={()=>void resolve()}>Resolve question</button></div></Modal>}
  </>;
}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/70 p-4"><div className="panel w-full max-w-xl p-5"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow">Codex decision flow</p><h2 className="mt-1 text-xl font-semibold text-white">{title}</h2></div><button onClick={onClose} className="text-slate-500 hover:text-white"><X/></button></div><div className="space-y-3">{children}</div></div></div>}
