import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { AlertOctagon, Plus, Scale, ShieldCheck, X } from 'lucide-react';
import { db } from '../db';
import { makeId } from '../lib/id';
import { PageHeader } from '../components/PageHeader';
import { StatusBadge } from '../components/StatusBadge';
import type { ConstraintRule } from '../types';

export function RulesPage() {
  const rules = useLiveQuery(() => db.rules.toArray(), []) ?? [];
  const [domain, setDomain] = useState('all'); const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: '', domain: 'Technology', rule: '', rationale: '', severity: 'strong' as ConstraintRule['severity'] });
  const domains = [...new Set(rules.map((rule) => rule.domain))].sort(); const visible = rules.filter((rule) => domain === 'all' || rule.domain === domain).sort((a,b) => ({hard:0,strong:1,soft:2}[a.severity] - {hard:0,strong:1,soft:2}[b.severity]));
  async function addRule() { if (!form.name.trim() || !form.rule.trim()) return; const now = new Date().toISOString(); await db.rules.add({ id: makeId('rule'), projectId:'project_analog_schism', ...form, canonStatus:'draft', examples:[], exceptions:[], relatedEntryIds:[], createdAt:now, updatedAt:now }); setOpen(false); setForm({ name:'', domain:'Technology', rule:'', rationale:'', severity:'strong' }); }
  return <>
    <PageHeader eyebrow="Consistency and technical realism" title="Constraint & Rules Engine" description="Hard rules cannot be casually bypassed. Strong rules preserve tone and stakes; soft rules describe the usual pattern." actions={<button className="button-primary" onClick={() => setOpen(true)}><Plus size={17} /> Add rule</button>} />
    <section className="panel mb-4 flex flex-wrap items-center gap-2 p-3"><button onClick={() => setDomain('all')} className={domain === 'all' ? 'button-primary !py-2' : 'button-secondary !py-2'}>All domains</button>{domains.map((item) => <button key={item} onClick={() => setDomain(item)} className={domain === item ? 'button-primary !py-2' : 'button-secondary !py-2'}>{item}</button>)}</section>
    <section className="grid gap-4 xl:grid-cols-2">{visible.map((rule) => <article key={rule.id} className="panel p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className={`grid size-10 shrink-0 place-items-center rounded-xl border ${rule.severity === 'hard' ? 'border-red-300/20 bg-red-300/10 text-red-200' : rule.severity === 'strong' ? 'border-amber-300/20 bg-amber-300/10 text-amber-200' : 'border-cyan-300/20 bg-cyan-300/10 text-cyan-200'}`}>{rule.severity === 'hard' ? <AlertOctagon size={19} /> : rule.severity === 'strong' ? <ShieldCheck size={19} /> : <Scale size={19} />}</div><div><div className="eyebrow">{rule.domain} // {rule.severity}</div><h2 className="mt-1 font-semibold text-white">{rule.name}</h2></div></div><StatusBadge status={rule.canonStatus} /></div><div className="mt-4 rounded-xl border border-white/10 bg-black/15 p-4 text-sm leading-6 text-slate-200">{rule.rule}</div><p className="mt-3 text-xs leading-5 text-slate-500"><span className="text-slate-400">Why:</span> {rule.rationale}</p>{rule.examples.length > 0 && <div className="mt-3 text-xs text-slate-500"><span className="text-slate-400">Example:</span> {rule.examples[0]}</div>}</article>)}</section>
    {open && <div className="fixed inset-0 z-[90] grid place-items-center bg-black/70 p-4"><div className="panel w-full max-w-xl p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">New world constraint</p><h2 className="mt-1 text-xl font-semibold text-white">Add rule</h2></div><button onClick={() => setOpen(false)} className="text-slate-500"><X /></button></div><div className="mt-5 space-y-3"><input className="input" value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="Rule name" /><input className="input" value={form.domain} onChange={(e) => setForm({...form,domain:e.target.value})} placeholder="Domain" /><textarea className="input min-h-24" value={form.rule} onChange={(e) => setForm({...form,rule:e.target.value})} placeholder="State the constraint clearly" /><textarea className="input min-h-20" value={form.rationale} onChange={(e) => setForm({...form,rationale:e.target.value})} placeholder="Why does this rule exist?" /><select className="input" value={form.severity} onChange={(e) => setForm({...form,severity:e.target.value as ConstraintRule['severity']})}><option value="hard">Hard — no exceptions without a canon decision</option><option value="strong">Strong — preserves stakes and tone</option><option value="soft">Soft — normal pattern</option></select></div><div className="mt-6 flex justify-end gap-2"><button className="button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button-primary" onClick={() => void addRule()}>Add draft rule</button></div></div></div>}
  </>;
}
