import { useEffect, useRef, useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { ArchiveRestore, DatabaseBackup, Download, FileDown, FileUp, Plus, RotateCcw, Save, Trash2 } from 'lucide-react';
import { db, resetDatabase } from '../db';
import { makeId } from '../lib/id';
import { downloadText } from '../lib/text';
import { PageHeader } from '../components/PageHeader';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { buildExport, exportToMarkdown, restoreExport } from '../services/exportService';
import { parseWorldBibleMarkdown } from '../services/markdownImport';
import type { ModuleType, Snapshot, SourceDocument } from '../types';

export function SettingsPage(){
  const data=useLiveQuery(async()=>({project:await db.projects.toCollection().first(),modules:await db.moduleTypes.toArray(),sources:await db.sources.toArray(),snapshots:await db.snapshots.orderBy('createdAt').reverse().toArray()}),[]);
  const [name,setName]=useState('');const [description,setDescription]=useState('');const [moduleName,setModuleName]=useState('');const [moduleIcon,setModuleIcon]=useState('Box');const [message,setMessage]=useState('');const [resetOpen,setResetOpen]=useState(false);const jsonInput=useRef<HTMLInputElement | null>(null);const mdInput=useRef<HTMLInputElement | null>(null);
  const project=data?.project;
  useEffect(()=>{if(project){setName(project.name);setDescription(project.description)}},[project?.id]);
  async function saveProject(){if(!project)return;await db.projects.update(project.id,{name,description,updatedAt:new Date().toISOString()});flash('Project settings saved.');}
  async function addModule(){const clean=moduleName.trim();if(!clean)return;const id=clean.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||makeId('module');if(await db.moduleTypes.get(id)){flash('A module with that identifier already exists.');return}const now=new Date().toISOString();const record:ModuleType={id,name:clean,singular:clean,plural:clean.endsWith('s')?clean:`${clean}s`,icon:moduleIcon||'Box',description:'User-defined lore module.',colour:'#8fd7bd',timelineEnabled:false,relationshipsEnabled:true,defaultFields:[],createdAt:now,updatedAt:now};await db.moduleTypes.add(record);setModuleName('');flash(`Added ${clean} module.`)}
  async function exportJson(){const payload=await buildExport();downloadText('the-analog-schism.schism.json',JSON.stringify(payload,null,2));}
  async function exportMarkdown(){const payload=await buildExport();downloadText('the-analog-schism-world-bible.md',exportToMarkdown(payload), 'text/markdown');}
  async function snapshot(){const payload=await buildExport();const name=prompt('Snapshot name','Before lore expansion');if(!name)return;const record:Snapshot={id:makeId('snapshot'),projectId:payload.project.id,name,payload,createdAt:new Date().toISOString()};await db.snapshots.add(record);flash('Snapshot created.');}
  async function restoreSnapshot(item:Snapshot){if(!confirm(`Restore snapshot “${item.name}”? Current data will be replaced.`))return;await restoreExport(item.payload);flash('Snapshot restored.');location.reload();}
  async function importJson(file:File){try{const parsed=JSON.parse(await file.text());await restoreExport(parsed);flash('Backup restored. Reloading…');setTimeout(()=>location.reload(),500)}catch(error){flash(`Import failed: ${error instanceof Error?error.message:String(error)}`)}}
  async function importMarkdown(file:File){if(!project)return;const text=await file.text();const sourceId=makeId('source');const source:SourceDocument={id:sourceId,projectId:project.id,title:file.name.replace(/\.[^.]+$/,''),sourceType:'world-bible',originalText:text,fileName:file.name,authoritative:false,createdAt:new Date().toISOString()};const result=parseWorldBibleMarkdown(text,project.id,sourceId,data?.modules??[]);await db.transaction('rw',[db.sources,db.entries],async()=>{await db.sources.add(source);await db.entries.bulkAdd(result.entries)});flash(`Imported ${result.report.created} sections; ${result.report.needsReview} need classification review.`)}
  function flash(value:string){setMessage(value);setTimeout(()=>setMessage(''),3500)}
  async function reset(){await resetDatabase();setResetOpen(false);location.reload()}
  return <>
    <PageHeader eyebrow="Local data, schema and backups" title="Settings & Backup" description="Everything is stored in this browser’s IndexedDB. Export regular backups before clearing browser data or moving devices." />
    {message&&<div className="mb-4 rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-3 text-sm text-emerald-100">{message}</div>}
    <div className="grid gap-4 xl:grid-cols-2">
      <section className="panel p-5"><p className="eyebrow">Project identity</p><h2 className="mt-1 text-lg font-semibold text-white">World settings</h2><div className="mt-4 space-y-3"><label className="block"><span className="text-xs text-slate-400">Project name</span><input className="input mt-1" value={name} onChange={e=>setName(e.target.value)}/></label><label className="block"><span className="text-xs text-slate-400">Description</span><textarea className="input mt-1 min-h-28" value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="button-primary" onClick={()=>void saveProject()}><Save size={16}/> Save settings</button></div></section>
      <section className="panel p-5"><p className="eyebrow">Portable data</p><h2 className="mt-1 text-lg font-semibold text-white">Export and restore</h2><div className="mt-4 grid gap-2 sm:grid-cols-2"><button className="button-primary" onClick={()=>void exportJson()}><Download size={16}/> Full .schism.json</button><button className="button-secondary" onClick={()=>void exportMarkdown()}><FileDown size={16}/> Clean world bible</button><button className="button-secondary" onClick={()=>jsonInput.current?.click()}><ArchiveRestore size={16}/> Restore JSON</button><button className="button-secondary" onClick={()=>mdInput.current?.click()}><FileUp size={16}/> Import Markdown</button><button className="button-secondary sm:col-span-2" onClick={()=>void snapshot()}><DatabaseBackup size={16}/> Create named snapshot</button></div><input ref={jsonInput} hidden type="file" accept=".json,.schism.json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void importJson(f);e.currentTarget.value=''}}/><input ref={mdInput} hidden type="file" accept=".md,text/markdown,text/plain" onChange={e=>{const f=e.target.files?.[0];if(f)void importMarkdown(f);e.currentTarget.value=''}}/><p className="mt-4 text-xs leading-5 text-slate-500">JSON restore validates the schema and replaces the current project. Markdown import adds provisional structured records and preserves the source document.</p></section>
      <section className="panel p-5"><p className="eyebrow">Modular schema</p><h2 className="mt-1 text-lg font-semibold text-white">Lore module types</h2><div className="mt-4 flex gap-2"><input className="input" value={moduleName} onChange={e=>setModuleName(e.target.value)} placeholder="Creature, language, vehicle…"/><input className="input max-w-32" value={moduleIcon} onChange={e=>setModuleIcon(e.target.value)} placeholder="Icon name"/><button className="button-primary" onClick={()=>void addModule()}><Plus size={16}/></button></div><div className="mt-4 flex max-h-72 flex-wrap content-start gap-2 overflow-y-auto">{data?.modules.map(module=><span key={module.id} className="rounded-full border border-white/10 px-2.5 py-1 text-xs text-slate-400">{module.singular}</span>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">New module types immediately appear in the library and editor. Their stable ID is generated from the label.</p></section>
      <section className="panel p-5"><p className="eyebrow">Provenance</p><h2 className="mt-1 text-lg font-semibold text-white">Source documents</h2><div className="mt-4 space-y-2">{data?.sources.map(source=><div key={source.id} className="rounded-xl border border-white/10 p-3"><div className="flex items-center justify-between gap-3"><div className="truncate text-sm text-slate-200">{source.title}</div>{source.authoritative&&<span className="rounded-full border border-emerald-300/15 bg-emerald-300/5 px-2 py-0.5 font-mono text-[9px] uppercase tracking-wider text-emerald-200">Authoritative</span>}</div><div className="mt-1 text-xs text-slate-600">{source.fileName??source.sourceType} · {source.originalText.length.toLocaleString()} characters</div></div>)}</div></section>
      <section className="panel p-5 xl:col-span-2"><p className="eyebrow">Named recovery points</p><h2 className="mt-1 text-lg font-semibold text-white">Snapshots</h2><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{data?.snapshots.map(item=><div key={item.id} className="rounded-xl border border-white/10 p-3"><div className="font-medium text-slate-200">{item.name}</div><div className="mt-1 text-xs text-slate-600">{new Date(item.createdAt).toLocaleString()}</div><div className="mt-3 flex gap-2"><button className="button-secondary !py-2" onClick={()=>void restoreSnapshot(item)}><RotateCcw size={14}/> Restore</button><button className="button-danger !py-2" onClick={()=>void db.snapshots.delete(item.id)}><Trash2 size={14}/></button></div></div>)}{data?.snapshots.length===0&&<p className="text-sm text-slate-500">No named snapshots yet.</p>}</div></section>
      <section className="panel border-red-300/10 p-5 xl:col-span-2"><p className="eyebrow !text-red-300/70">Danger zone</p><h2 className="mt-1 text-lg font-semibold text-white">Reset local database</h2><p className="mt-2 text-sm text-slate-500">Deletes local edits and reloads the authoritative v1 seed. Export a backup first.</p><button className="button-danger mt-4" onClick={()=>setResetOpen(true)}><Trash2 size={16}/> Reset Schism Codex</button></section>
    </div>
    <ConfirmDialog open={resetOpen} title="Reset the entire local codex?" description="All local entries, writing notes, imported sources and revisions will be deleted. The original World Bible seed will then be restored." destructive confirmLabel="Reset everything" onCancel={()=>setResetOpen(false)} onConfirm={()=>void reset()}/>
  </>
}
